language: node_js
node_js:
  - "12"
  - "14"

sudo: false

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
  - npm i -g hyperswarm-web
  - hyperswarm-web &
  - node --version
  - npm i npm@latest

script:
  - fossa init
  - fossa analyze
  - npm test -- --allow-chrome-as-root

after_success: 
  - npm run coverage
  - fossa test
